services:
  ror:
    image: ghcr.io/computroniks/ror-docker:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      ELASTIC_HOST: elasticsearch7
      ELASTIC_PORT: 9200
      ELASTIC_PASSWORD: changeme
      ROR_BASE_URL: http://ror
      DATA_STORE: data.dev.ror.org
    depends_on:
      - elasticsearch7

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      cluster.routing.allocation.disk.threshold_enabled: "false"
    volumes:
      - ./data/ror/elasticsearch:/var/lib/elasticsearch/data